In [ ]:
import numpy as np

Creating numpy arrays

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
n_list = [[1,2],[3,4],[5,6]]
n_list

[[1, 2], [3, 4], [5, 6]]

In [ ]:
np.array(n_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

Built-in methods

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,110,4)

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108])

In [ ]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(100,150,7)

array([100, 107, 114, 121, 128, 135, 142, 149])

In [ ]:
np.arange(100,150,5)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

zeroes and ones

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Linspace

In [ ]:
np.linspace(0,110,5)

array([  0. ,  27.5,  55. ,  82.5, 110. ])

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
np.linspace(1000,2000,25)

array([1000.        , 1041.66666667, 1083.33333333, 1125.        ,
       1166.66666667, 1208.33333333, 1250.        , 1291.66666667,
       1333.33333333, 1375.        , 1416.66666667, 1458.33333333,
       1500.        , 1541.66666667, 1583.33333333, 1625.        ,
       1666.66666667, 1708.33333333, 1750.        , 1791.66666667,
       1833.33333333, 1875.        , 1916.66666667, 1958.33333333,
       2000.        ])

In [ ]:
np.linspace(1,2,50)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

Eye

In [ ]:
np.eye(4)  # to create identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

random with default range:(0,1)

In [ ]:
np.random.rand(5)

array([0.52036335, 0.98173768, 0.26696394, 0.73904633, 0.44466291])

In [ ]:
np.random.rand(5,5)

array([[0.76418428, 0.25845754, 0.81852584, 0.63982523, 0.82076707],
       [0.08876785, 0.52819229, 0.48340713, 0.62292254, 0.49404931],
       [0.2803883 , 0.36049841, 0.08382125, 0.51455482, 0.49539742],
       [0.11425283, 0.02766034, 0.46435352, 0.79212741, 0.02956481],
       [0.99424852, 0.6805574 , 0.0964284 , 0.63848123, 0.00797071]])

In [ ]:
# randn to generate samples following normal distribution
np.random.randn(4)

array([-1.31297284,  0.12833727, -0.78154532, -0.93541579])

In [ ]:
# randint to generate random integers in a given range
np.random.randint(3,6)

3

In [ ]:
np.random.randint(1,3,5) # includes value from 1 and 2

array([2, 2, 2, 2, 2])

In [ ]:
np.random.randint(10,25)

19

In [ ]:
np.random.randint(1,10,3)

array([8, 8, 5])

Reshape

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr.shape

(10,)

In [ ]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Q. Create an array with 20 elements populate your array in such a way that your elements should be between 200 and 500
print the dimension of the created array using appropriate array
print all the possiiblities of the created array with various dimensions


In [ ]:
arr = np.random.randint(200,500,20)
arr.shape

(20,)

In [ ]:
arr.reshape(10,2)

array([[441, 391],
       [418, 240],
       [370, 210],
       [483, 340],
       [486, 321],
       [297, 247],
       [441, 497],
       [497, 346],
       [438, 234],
       [346, 336]])

In [ ]:
arr.reshape(2,10)

array([[441, 391, 418, 240, 370, 210, 483, 340, 486, 321],
       [297, 247, 441, 497, 497, 346, 438, 234, 346, 336]])

In [ ]:
arr.reshape(5,4)

array([[441, 391, 418, 240],
       [370, 210, 483, 340],
       [486, 321, 297, 247],
       [441, 497, 497, 346],
       [438, 234, 346, 336]])

In [ ]:
arr.reshape(4,5)

array([[441, 391, 418, 240, 370],
       [210, 483, 340, 486, 321],
       [297, 247, 441, 497, 497],
       [346, 438, 234, 346, 336]])

In [ ]:
arr.reshape(1,20)

array([[441, 391, 418, 240, 370, 210, 483, 340, 486, 321, 297, 247, 441,
        497, 497, 346, 438, 234, 346, 336]])

In [ ]:
arr.reshape(20,1)

array([[441],
       [391],
       [418],
       [240],
       [370],
       [210],
       [483],
       [340],
       [486],
       [321],
       [297],
       [247],
       [441],
       [497],
       [497],
       [346],
       [438],
       [234],
       [346],
       [336]])

In [ ]:
arr.max()

497

In [ ]:
arr.min()

210

In [ ]:
arr.dtype

dtype('int64')

Indexing and Selection

In [ ]:
arr[2]

418

In [ ]:
arr[3:15]

array([240, 370, 210, 483, 340, 486, 321, 297, 247, 441, 497, 497])

In [ ]:
arr[:4] #(0 to 4)

array([441, 391, 418, 240])

In [ ]:
arr[10:] #(10 to end)

array([297, 247, 441, 497, 497, 346, 438, 234, 346, 336])

Broadcasting

In [ ]:
#since a and a*b is similar array..broadcasting helps in multiplication as memory is saved
a = np.array([5,10,20])
b = 2
a*b

array([10, 20, 40])

In [ ]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100, 210, 483, 340, 486, 321, 297, 247, 441,
       497, 497, 346, 438, 234, 346, 336])

Selection

In [ ]:
arr>350

array([False, False, False, False, False, False,  True, False,  True,
       False, False, False,  True,  True,  True, False,  True, False,
       False, False])

In [ ]:
bool_arr = arr>122
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
arr[arr>177]

array([210, 483, 340, 486, 321, 297, 247, 441, 497, 497, 346, 438, 234,
       346, 336])

Min max

In [ ]:
arr.argmax()

13

In [ ]:
arr.argmin()

0

In [ ]:
arr.dtype

dtype('int64')

Indexing in 2D array

In [ ]:
a2d = np.array(([2,4,8],[10,12,14],[16,18,20]))
a2d.shape

(3, 3)

In [ ]:
a2d

array([[ 2,  4,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [ ]:
a2d[0]

array([2, 4, 8])

In [ ]:
a2d[1][1]

12

In [ ]:
a2d[1,2]

14

In [ ]:
#Shape (2,2) from top right corner
a2d[:2,1:]
#[row,col]

array([[ 4,  8],
       [12, 14]])

In [ ]:
#to print all the columns of the first row - row 0
a2d[0:1,:]

array([[2, 4, 8]])